export * from '../adminMainPage/pages/RegisterGuard'
export * from './components/Navbar'
export * from './pages/ListaAlumnos'
export * from './components/BikeList'
export * from './pages/ListaIngresos'